#!/usr/bin/env bash
# Seed CloudFuze MFT master secrets into HashiCorp Vault (KV v2).
# Run once against a Vault you control. In production these values are generated by your PKI/KMS
# and rotated on a schedule — this script just establishes the paths the app reads from.
#
# Env: VAULT_ADDR (default http://127.0.0.1:8200), VAULT_TOKEN
set -euo pipefail
export VAULT_ADDR="${VAULT_ADDR:-http://127.0.0.1:8200}"

# Enable a KV v2 mount for the product if not already present.
vault secrets enable -path=mft kv-v2 2>/dev/null || true

# JWT signing secret (HS384-capable length) and crypto-vault master key (32 bytes, base64).
# Generated fresh here; in prod source these from your KMS and never log them.
JWT_SECRET="${JWT_SECRET:-$(openssl rand -base64 48)}"
CRYPTO_MASTER_KEY="${CRYPTO_MASTER_KEY:-$(openssl rand -base64 32)}"
DB_PASSWORD="${DB_PASSWORD:-$(openssl rand -base64 24)}"

vault kv put mft/jwt        secret="$JWT_SECRET"
vault kv put mft/crypto     master_key="$CRYPTO_MASTER_KEY"
vault kv put mft/db         password="$DB_PASSWORD"

echo "Seeded mft/jwt, mft/crypto, mft/db into Vault at $VAULT_ADDR"
